### ISSUE TITLE
Third party modules?

### ISSUE THREAD

**Issue by technion** [efidiles/lodash-ts-imports-loader#1]
Hi,

Many thanks for writing this tool!

I'm wondering if there's a way I can get this to work with third party modules.
Specifically, I'm using Semantic-ui-react, which bundles lodash. It [documents](https://react.semantic-ui.com/usage) (scroll to the bottom) their troubles with webpack tree shaking, but as a Typescript non-babel user I haven't found their workarounds helpful.

I've tried fiddling with your recommended config to make it apply down node_modules but haven't had much luck - bringing a single semantic-ui-react component in seems to bundle the whole of lodash.

Have you had any experience of luck using this loader modules that themselves bundle lodash?

**Comment by efidiles** [comment]
@technion sorry for the late reply. 

I don't believe there is an easy to do what you need. 
A reason that comes to mind is that some of your direct dependencies or sub-dependecies will most likely reference / import a distribution bundle of lodash which is basically already a bundled js file and not the source code files of lodash. Consequently this module (lodash-ts-imports-loader) will not actually receive the source code in order to be able to rename the imports into ts 'tree-shakeable syntax'.

Lately I tend to make as much use of es6 as possible and only add as dependencies the individual lodash npm package that I really need. Also yarn's or npm5's lock files help with avoiding conflicts between different version of dependencies - or dependencies of dependencies.

hope that helps

**Comment by technion** [comment]
Hi,

No worries, thanks for the answer, I'll work with that!
